### ISSUE TITLE
disable delay on hover

### ISSUE THREAD

**Issue by MartinP7r** [PKM-er/obsidian-floating-toc-plugin#104]
When hovering over the toc to display the contents, there's a small delay.  
I don't expect there to be any performance reasons for the delay. Is it possible to show the TOC immediately?

**Comment by cumany** [comment]
The responsiveness can be adjusted in the appearance settings of floating toc using the style setting plugin.

**Comment by scambier** [comment]
Why is there a delay at all? This 100% looks like a performance bug so it's not obvious that you can set it to 0.

Some unsolicited advice: it would look better if the delay _also_ affected the background (so that it doesn't appear empty before popping the text), and/or if there was a fade in or a slide in.
